# Generated by Django 6.0.5 on 2026-05-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_accounts_user_id_accounts_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='id',
        ),
        migrations.AddField(
            model_name='accounts',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
